services:
  service1:
    build: ./services/service1
    container_name: service_1
    tty: true
    ports:
      - "8199:8199"
    volumes:
      - vstorage:/vstorage
    depends_on:
      - service2
      - storage
    networks:
      - service_network

  service2:
    build: ./services/service2
    container_name: service_2
    volumes:
      - vstorage:/vstorage
    networks:
      - service_network

  storage:
    build: ./services/storage
    container_name: storage
    volumes:
      - storage_data:/data
    networks:
      - service_network

volumes:
  vstorage:
    driver: local
    driver_opts:
      type: none
      device: ./vstorage
      o: bind
  storage_data:

networks:
  service_network:
    driver: bridge
