services:
  service1:
    build: ./services/service1
    container_name: service_1
    tty: true
    ports:
      - "8199:8199"
    depends_on:
      - service2
      - storage
    networks:
      - service_network

  service2:
    build: ./services/service2
    container_name: service_2
    networks:
      - service_network

  storage:
    build: ./services/storage
    container_name: storage
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
