services:
  service1:
    build: ./services/service1
    container_name: service_1
    depends_on:
      ""
    environment:
      - ""
    networks:
      - "" 

  service2:
    build: ./services/service2
    container_name: service_2
    depends_on:
      ""
    environment:
      - ""
    networks:
      - "" 

  storage:
    build: ./services/storage
    container_name: storage
    depends_on:
      ""
    environment:
      - ""
    networks:
      - "" 